services:
  s3:
    image: quay.io/minio/minio
    container_name: s3
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - minios3_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    networks:
      - compose

volumes:
  minios3_data: {}

networks:
  compose:
    external: true  # Using the existing network, not create a new one.
