services:
  mongodb:
    image: mongo:4.4
    hostname: mongodb
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017/tcp
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db/
    networks:
      - compose

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:secret@mongodb:27017/
      ME_CONFIG_BASICAUTH: 1
    networks:
      - compose

#  mongodb-exporter:
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "5"
#    hostname: mongodb-exporter
#    restart: always
#    stop_grace_period: 1m
#    image: mongodb-exporter:0.40.0
#    ports:
#      - "9126:9126"
#      - "9216:9216"
#    enviroment:
#      MONGODB_URI: mongodb://mongoadmin:secret@mongodb:27017
#    networks:
#      - compose

volumes:
  mongodb_data: {}

networks:
  compose:
    external: true  # Using the existing network, not create a new one.


