services:
  mongodb:
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    hostname: mongodb
    container_name: mongodb
    restart: always
    stop_grace_period: 1m
    image: mongo:latest
    ports:
      - 27017:27017/tcp
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db/
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 20s
      timeout: 20s
      retries: 6
    networks:
      - compose

#  mongodb-exporter:
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "5"
#    hostname: mongodb-exporter
#    restart: always
#    stop_grace_period: 1m
#    image: mongodb-exporter:0.40.0
#    ports:
#      - "9126:9126"
#      - "9216:9216"
#    enviroment:
#      MONGODB_URI: mongodb://mongoadmin:secret@mongodb:27017
#    networks:
#      - compose

#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    restart: always
#    ports:
#      - "28081:8081"
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongodb
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: changeme
#      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
#      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
#      ME_CONFIG_MONGODB_URL: mongo://mongoadmin:secret@mongodb:27017/ 
#    depends_on:
#      - mongodb
#    networks:
#      - compose

volumes:
  mongodb_data: {}

networks:
  compose:
    external: true  # Using the existing network, not create a new one.


