services:
  mginx:
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    hostname: nginx
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - 2084:80
    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static/:/var/www/static/:ro
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - compose

networks:
  compose:
    external: true  # Using the existing network, not create a new one.