services:
  redis:
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    hostname: redis
    restart: always
    stop_grace_period: 1m
    image: redis:7.0
    ports:
      - 6379:6379/tcp
    volumes:
      - ./data:/data
    healthcheck:
        test: ["CMD", "redis-cli","ping"]
        interval: 20s
        timeout: 20s
        retries: 6
    networks:
      - compose

#  redis-exporter:
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "5"
#    hostname: redis-exporter
#    restart: always
#    stop_grace_period: 1m
#    image: redis-exporter:1.61.0
#    ports:
#      - "9121:9121"
#    env_file:
#      - ./environments/redis-exporter.env
#	enviroments:
#		REDIS_ADDR=redis:6379
#    networks:
#      - compose

networks:
  compose:
    driver: bridge

